
# bind = , F5, exec, ~/.config/hypr/scripts/godot-debug-key.sh F5
# bind = , F8, exec, ~/.config/hypr/scripts/godot-debug-key.sh F8
bind = CTRL SHIFT SUPER, R, exec, sh -c 'PID=$(hyprctl activewindow -j | jq -r .pid); BIN=$(readlink /proc/$PID/exe); kill -9 "$PID" && sleep 0.3 && "$BIN" &'
bind = CTRL ALT, a, exec, wayland-keepass-autotype -d ~/keepassdb/keepass.kdbx -c 30
bind = CTRL ALT, s, exec, wayland-keepass-autotype -d ~/keepassdb/keepass.kdbx -c 30 --password-only
bind = CTRL ALT, d, exec, wayland-keepass-autotype -d ~/keepassdb/keepass.kdbx -c 30 --otp-only
bind = $mainMod SHIFT, G, exec, hyprctl keyword decoration:screen_shader "[[EMPTY]]"
bind = super, c, fullscreen
bind = SHIFT ALT, RETURN, fullscreen
bind = CONTROL, escape, exec, killall wtype ; hyprctl reload
# bind = CONTROL ALT, v, exec, wl-paste | wtype -m ctrl -m alt -p v -d 100 -s 300 -
# bind = CONTROL ALT SHIFT, v, exec, wl-paste | sed s/(.)/-k \1/g | wtype -m ctrl -m alt -p v -d 100 -s 300 -
bind = $mainMod, l, exec, hyprlock --no-fade-in
bind = CONTROL $mainMod, l, exec, armLock
# bind = SHIFT, Print, exec, hyprshot -m output
bind = , Print, exec, hyprshot -m window
# bind = CTRL ALT, T, exec, $terminal
# bind = $mainMod, Q, exec, $terminal
bind = CTRL SHIFT, Q, killactive,
# bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
# bind = CTRL $mainMod, E, exec, $fileManager
bind = SHIFT ALT, SPACE, togglefloating,
# bind = $mainMod, V, togglefloating,
# bind = $mainMod, R, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
# bind = $mainMod, J, togglesplit, # dwindle
bind = SHIFT ALT, RETURN, fullscreenstate,1 1

# bind = CTRL, code:90, exec, /run/current-system/sw/bin/kitten quick-access-terminal python3.14 ~/nixconf/home/cliphistViewer/main.py
bind = CTRL, KP_Insert, exec, /run/current-system/sw/bin/kitten quick-access-terminal python3.14 ~/nixconf/home/cliphistViewer/main.py
# bind = CTRL, KP_0, exec, kitten quick-access-terminal python3.14 ~/nixconf/home/cliphistViewer/main.py