bind = alt, space, submap, launcher
submap = launcher
bind = , v, exec, codium
bind = , v, submap, reset
bind = , b, exec, brave
bind = , b, submap, reset
bind = , p, exec, kitty pashare start
bind = , p, submap, reset
bind = , g, exec, godot-newest
bind = , g, submap, reset
bind = , s, exec, winspy
bind = , s, submap, reset
bind = , a, exec, audioMover ~/audio ~/audio/output ~/syncthing/media/audio
bind = , a, submap, reset
bind = , e, exec, thunar
bind = , e, submap, reset
# bind = , f, exec, QT_QPA_PLATFORM=xcb LC_ALL=C opensnitch-ui
# bind = , f, submap, reset
bind = , t, exec, kitty
bind = , t, submap, reset
bind = , x, exec, xdm
bind = , x, submap, reset
bind = , catchall, submap, reset

submap = reset

bind = CTRL SHIFT, SPACE, exec, anyrun
