bind = shift, Print, exec, ~/.config/hypr/scripts/toggleRec.sh
bind = CONTROL SHIFT, Print, exec, grim -g "$(slurp)" - | tesseract - - stdout | wl-copy
bind = CONTROL SHIFT, f9, exec, flashbackSaveAndOpen
bind = CONTROL, f9, exec, killall -SIGUSR1 gpu-screen-recorder
bind = CONTROL, Print, exec, hyprshot -m region --raw | satty --filename -
# bind = CONTROL, Print, exec, hyprshot -m region --raw | swappy -f -


bind = $mainMod, G, exec, ~/.config/hypr/scripts/clone_view.sh

bind = CONTROL ALT SHIFT, slash, exec, ~/.config/hypr/scripts/toggle_inwhi.sh
