# bind = $mainMod, 1, movefocus, l
# bind = $mainMod, 4, movefocus, l
# bind = $mainMod, 3, movefocus, r
# bind = $mainMod, 6, movefocus, r
# bind = $mainMod, 2, movefocus, u
# bind = $mainMod, 5, movefocus, d
bind = $mainMod, a, workspace, 1
bind = $mainMod, s, workspace, 2
bind = $mainMod, d, workspace, 3
bind = $mainMod, f, workspace, 4
# bind = $mainMod, q, workspace, 5
# bind = $mainMod, w, workspace, 6
bind = $mainMod, e, workspace, 7
bind = $mainMod, r, workspace, 8
bind = SUPER, Down, movetoworkspacesilent, 8
bind = $mainMod SHIFT, a, movetoworkspace, 1
bind = $mainMod SHIFT, s, movetoworkspace, 2
bind = $mainMod SHIFT, d, movetoworkspace, 3
bind = $mainMod SHIFT, f, movetoworkspace, 4
bind = $mainMod SHIFT, q, movetoworkspace, 5
bind = $mainMod SHIFT, w, movetoworkspace, 6
bind = $mainMod SHIFT, e, movetoworkspace, 7
bind = $mainMod SHIFT, r, movetoworkspace, 8
bind = $mainMod, z, togglespecialworkspace, magic
bind = $mainMod SHIFT, z, movetoworkspace, special:magic
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

binds {
  allow_workspace_cycles = true
}
bind = $mainMod, q,         layoutmsg, focus l
bind = $mainMod, w,         layoutmsg, focus r
bind = $mainMod, tab,       layoutmsg, focus l
bind = $mainMod SHIFT, tab, layoutmsg, focus r

# bind = $mainMod, q,         exec, ~/.config/hypr/scripts/focus-dir.sh l
# bind = $mainMod, w,         exec, ~/.config/hypr/scripts/focus-dir.sh r
# bind = $mainMod, tab,       exec, ~/.config/hypr/scripts/focus-dir.sh l
# bind = $mainMod SHIFT, tab, exec, ~/.config/hypr/scripts/focus-dir.sh r