plugin:dynamic-cursors {
  # enables the plugin
  enabled = true

  # sets the cursor behaviour, supports these values:
  # tilt    - tilt the cursor based on x-velocity
  # rotate  - rotate the cursor based on movement direction
  # stretch - stretch the cursor shape based on direction and velocity
  # none    - do not change the cursors behaviour
  mode = stretch

  # minimum angle difference in degrees after which the shape is changed
  # smaller values are smoother, but more expensive for hw cursors
  threshold = 2
  shake {
    # why is this the only one enabled by default?
    enabled = false
  }
  stretch {
    # controls how much the cursor is stretched
    # this value controls at which speed (px/s) the full stretch is reached
    # the full stretch being twice the original length
    limit = 500

    # relationship between speed and stretch amount, supports these values:
    # linear             - a linear function is used
    # quadratic          - a quadratic function is used
    # negative_quadratic - negative version of the quadratic one, feels more aggressive
    # see `activation` in `src/mode/utils.cpp` for how exactly the calculation is done
    function = quadratic

    # time window (ms) over which the speed is calculated
    # higher values will make slow motions smoother but more delayed
    window = 120
  }
}
source = ~/