windowrule {
  # Ignore maximize requests from all apps. You'll probably like this.
  name = suppress-maximize-events
  match:class = .*

  suppress_event = maximize
}


windowrule {
  # Fix some dragging issues with XWayland
  name = a
  match:class = ^yad$
  float = true
  fullscreen = false
  pin = true

  center=1
}
windowrule {
  # Fix some dragging issues with XWayland
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false

  no_focus = true
}
windowrule {
  name = fzenity
  match:class = ^zenity$
  fullscreen = false
  pin = true
  stay_focused = true
  focus_on_activate = true
  allows_input = true
  center = true
}
windowrule {
  name = asd
  match:class = ^xdman-Main$
  match:title = ^Xtreme Download Manager$
  workspace = 8
}

# Hyprland-run windowrule
windowrule {
  name = move-hyprland-run

  match:class = hyprland-run

  move = 20 monitor_h-120
  float = yes
}

windowrule = workspace 1, match:class ^codium$, match:title negative:^(Save As|Open (File|Folder))$, match:float false
windowrule = float true, match:title ^(Save As|Open (File|Folder))$, match:class ^codium$, center 1, size (monitor_w*.8) (monitor_h*.8), move ((monitor_w*0.5)-(monitor_w*.8/2)) ((monitor_h*0.5)-(monitor_h*.8/2)), dim_around 1, stay_focused 0
windowrule = float true, match:title ^(Open file)$, match:class ^Losslesscut$, center 1, size (monitor_w*.8) (monitor_h*.8), move ((monitor_w*0.5)-(monitor_w*.8/2)) ((monitor_h*0.5)-(monitor_h*.8/2)), dim_around 1, stay_focused 0
windowrule = opacity 1.0 1.0, match:title ^Global Progress$
windowrule = float true, match:title ^Global Progress$
windowrule = float true, match:title ^Save As$, match:class ^brave-browser$
windowrule = float true, match:title ^Save File$, match:class ^brave$, center 1, size (monitor_w*.8) (monitor_h*.8), move ((monitor_w*0.5)-(monitor_w*.8/2)) ((monitor_h*0.5)-(monitor_h*.8/2)), dim_around 1, stay_focused 0
windowrule = match:title ^Beatblock$, match:class ^Beatblock$, fullscreen on
windowrule = workspace 2, match:class ^brave-browser$

windowrule = no_max_size 1, match:class ^steam_app_default$, match:title ^Eets$
windowrule = fullscreen 1, match:class ^steam_app_default$, match:title ^Eets$
windowrule = fullscreen_state 2, match:class ^steam_app_default$, match:title ^Eets$

# windowrule = move (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.5)), match:title ^Global Progress$

windowrule = pin true, match:title ^HyprSpy$
windowrule = float true, match:title ^HyprSpy$

windowrule = pin true, match:title ^Browser Selector$, match:class ^Tk$
windowrule = float true, match:title ^Browser Selector$, match:class ^Tk$
windowrule = float true, match:title ^Browser Selector$, match:class ^Tk$, center 1, size (monitor_w*.8) (monitor_h*.8), move ((monitor_w*0.5)-(monitor_w*.8/2)) ((monitor_h*0.5)-(monitor_h*.8/2)), dim_around 1, stay_focused 0
# windowrule = pin true, match:title ^Global Progress$

# windowrule = no_focus true, match:title ^Global Progress$

# windowrule = no_blur true, match:title ^Global Progress$
# windowrule = decorate false, match:title ^Global Progress$