#!/usr/bin/env bash

# Exit immediately if no file is provided
if [ -z "$1" ]; then
  echo "Error: Please provide a video file path."
  echo "Usage: $0 /path/to/video.mp4"
  exit 1
fi

INPUT_PATH=$(realpath "$1")
INPUT_DIR=$(dirname "$INPUT_PATH")

# Run the transcription tool
docker run -it --rm \
  --device nvidia.com/gpu=all \
  -e HF_TOKEN \
  -v "$HOME/.cache/huggingface:/root/.cache/huggingface/hub" \
  -v "$INPUT_PATH:/app/input/video.mp4" \
  -v "$INPUT_DIR:/app/output" \
  ghcr.io/sirozha1337/faster-auto-subtitle:latest \
  --model medium --output_type srt --task transcribe

# Safely rename video.srt to [original_name].srt
if [ -f "$INPUT_DIR/video.srt" ]; then
  mv "$INPUT_DIR/video.srt" "${INPUT_PATH%.*}.srt"
  echo "Success! Subtitles saved to: ${INPUT_PATH%.*}.srt"
else
  echo "Error: video.srt was not generated by the container."
fi
