[General]
name = "arrow"
description = "Generated Hyprland cursor: arrow"
version = 1

[cursors.pointer]
hotspot_x = 0
hotspot_y = 0
fps = 24
[[cursors.pointer.frames]]
path = "arrow_000.png"

[[cursors.pointer.frames]]
path = "arrow_001.png"

[[cursors.pointer.frames]]
path = "arrow_002.png"

[[cursors.pointer.frames]]
path = "arrow_003.png"

[[cursors.pointer.frames]]
path = "arrow_004.png"

[[cursors.pointer.frames]]
path = "arrow_005.png"

[[cursors.pointer.frames]]
path = "arrow_006.png"

[[cursors.pointer.frames]]
path = "arrow_007.png"

[[cursors.pointer.frames]]
path = "arrow_008.png"

[[cursors.pointer.frames]]
path = "arrow_009.png"

[[cursors.pointer.frames]]
path = "arrow_010.png"

[[cursors.pointer.frames]]
path = "arrow_011.png"

[[cursors.pointer.frames]]
path = "arrow_012.png"

[[cursors.pointer.frames]]
path = "arrow_013.png"

[[cursors.pointer.frames]]
path = "arrow_014.png"

[[cursors.pointer.frames]]
path = "arrow_015.png"

[[cursors.pointer.frames]]
path = "arrow_016.png"

[[cursors.pointer.frames]]
path = "arrow_017.png"

[[cursors.pointer.frames]]
path = "arrow_018.png"

[[cursors.pointer.frames]]
path = "arrow_019.png"

[[cursors.pointer.frames]]
path = "arrow_020.png"

[[cursors.pointer.frames]]
path = "arrow_021.png"

[[cursors.pointer.frames]]
path = "arrow_022.png"

[[cursors.pointer.frames]]
path = "arrow_023.png"

[[cursors.pointer.frames]]
path = "arrow_024.png"

[[cursors.pointer.frames]]
path = "arrow_025.png"

[[cursors.pointer.frames]]
path = "arrow_026.png"

[[cursors.pointer.frames]]
path = "arrow_027.png"

[[cursors.pointer.frames]]
path = "arrow_028.png"

[[cursors.pointer.frames]]
path = "arrow_029.png"

