# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-28439dc9-600a-4b2e-a170-5627335aea46";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-28439dc9-600a-4b2e-a170-5627335aea46".device =
    "/dev/disk/by-uuid/28439dc9-600a-4b2e-a170-5627335aea46";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5CDB-9BD1";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # swapDevices =
  #   [ { device = "/dev/mapper/luks-b7bc4b47-2765-48c4-9068-ee0083727616"; }
  #   ];
swapDevices = [
  { device = "/swapfile"; size = 20480; }  # Set the swap file size in MB (2048MB in this case)
];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
