# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  ...
}:

{
  imports = [ ];
  boot = {
    initrd = {
      availableKernelModules = [
        "ata_piix"
        "ohci_pci"
        "ehci_pci"
        "ahci"
        "sd_mod"
        "sr_mod"
      ];
      kernelModules = [ ];
    };
    kernelModules = [ ];
    extraModulePackages = [ ];
  };
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/48e8d2cb-ccbc-4fa3-b081-82a10051aa70";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/06BB-CB36";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/4bd3a4f0-fe5f-4a02-9a6c-54bea110f47e"; }
  ];
  nixpkgs = {
    hostPlatform = lib.mkDefault "x86_64-linux";
  };
  virtualisation = {
    virtualbox = {
      guest = {
        enable = true;
      };
    };
  };
}
