{
  ln,
  inputs,
  pkgs,
  userConfig,
  config,
  ...
}:
{
  # home.activation.copy-hyprland-settings = ''
  #   echo "Copying hyprland settings..."
  #   mkdir -p "$HOME/.config/hypr/"
  #   mkdir -p "$HOME/.config/hypr/shaders"
  #   cp -f ${./hyprland.conf} "$HOME/.config/hypr/hyprland.conf"
  #   # sudo cp -fr ${./shaders} "$HOME/.config/hypr/shaders"
  # '';
  # home.file.".config/hypr/hyprland.conf".source = ./hyprland.conf;
  # home.file.".config/hypr/shaders".source = ./shaders;
  # sudo ln -sf /home/nyx/nixconf/home/hyprland/hyprland.conf "$HOME/.config/hypr/hyprland.conf"
  home.file = {
    # Link the main Hyprland config file
    ".config/hypr/hyprland.conf".source = ln "${userConfig.nixConf}/home/hyprland/hyprland.conf";
    ".config/hypr/shaders" = {
      source = ln "${userConfig.nixConf}/home/hyprland/shaders";
      recursive = true;
    };
  };
  wayland.windowManager.hyprland = {
    enable = true;
    # Tell HM to write its generated stuff to a different filename
    # This avoids the "Conflicting managed target files" error
    extraConfig = ''
      # This file is generated by Nix/Home Manager
      # Do not edit manually
      exec-once = hyprctl plugin load ${
        inputs.hypr-dynamic-cursors.packages.${pkgs.system}.hypr-dynamic-cursors
      }/lib/libhypr-dynamic-cursors.so

      plugin {
          dynamic-cursors {
              enabled = true
          }
      }
    '';
  };

  # Redirect the HM-generated config to its own file
  xdg.configFile."hypr/hm.conf".text = config.wayland.windowManager.hyprland.extraConfig;
  # // (
  #   # Map over the files in the ./shaders directory
  #   builtins.mapAttrs (name: value: {
  #     source = ln "${userConfig.nixConf}/home/hyprland/shaders/${name}";
  #   }) (builtins.readDir ./shaders)
  # );
  #    echo "Linking hyprland settings..."

  #    mkdir -p "$HOME/.config/hypr"
  #    #rm "$HOME/.config/hypr/hyprland.conf" >& /dev/null
  #    ln -f "$HOME/nixconf/home/hyprland/hyprland.conf" "$HOME/.config/hypr/hyprland.conf"
  #  '';
  # home.file.".config/hypr/hyprland.conf".source = ./hyprland.conf;
}
