general {
  ignore_empty_input=true
  immediate_render=true
  hide_cursor = true
}

background {
  monitor =
  path = ~/.config/hypr/wallpapers/wallpaper.png
  color = rgba(25, 20, 20, 1.0)
  crossfade_time = 0
}
animations{
  enabled=false
  bezier = linear, 0, 1, 0, 0
  animation = fade, 0, 1.8, linear
}
label {
  monitor =
  text = cmd[update:1000] echo -e "$(LC_TIME=en_US.UTF-8 date +"%A, %B %d")"|gowoify
  color = rgba(141, 0, 0, 0.9)
  font_size = 25
  font_family = SF Pro Display Semibold
  position = 0, 350
  halign = center
  valign = center
}
label {
  monitor =
  text = cmd[update:1000] echo "<span>$(date +"%H:%M"|gowoify)</span>"
  color = rgba(223, 0, 0, 0.9)
  font_size = 120
  font_family = SF Pro Display Bold
  position = 0, 230
  halign = center
  valign = center
}
label {
  monitor =
  text = cmd[update:300000] echo "$(curl -s 'wttr.in?T&d&q&1' | sed 's/\x1b\[[0-9;]*m//g')"|gowoify -e -a -m
  color = rgba(0, 0, 0, 0.7)
  font_size = 18
  font_family=monospace
  position = 0, -300
  halign = center
  valign = top
}

# image {
#   monitor =
#   path = /tmp/wttr.png
#   reload_time = 300
#   reload_cmd = curl -s "https://wttr.in/pulaski,%20virginia,%20us.png?d&q&1" -o /tmp/wttr.png
#   position = 0, -500
#   halign = center
#   valign = top
#   size = 400  # adjust to taste
#   rounding = 0
# }

input-field {
  size = 0%, 0k%
  outline_thickness = 3
  inner_color = rgba(0, 0, 0, 0.0) # no fill

  outer_color = rgba(0000ffff)
  check_color=rgba(00ff00ff)
  fail_color=rgba(ff0000ff)

  font_color = rgba(143, 143, 143, 0)
  fade_on_empty = false
  rounding = 100

  position = 0, -420
  halign = center
  valign = center
}